- name: Download the Elastic File
  become: true
  get_url:
    url: https://artifacts.elastic.co/downloads/apm/apm-server-{{ elastic_version }}-amd64.deb
    dest: /tmp
    mode: 0440
  when: elastic_flavor is defined and elastic_flavor == "pgdg"

- name: Installing the Elastic File
  become: true
  apt:
    deb: /tmp/apm-server-{{ elastic_version }}-amd64.deb

- name: Update apt-get repo and cache
  become: true
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Changing the apm-server config file
  become: true
  template:
    src: apm-server.yml.j2
    dest: '/etc/apm-server/apm-server.yml'

- name: starting the apm-server service
  become: true
  command: "service apm-server start"