---
- name: Create List of nodes to be added into Cluster
  set_fact: nodelist1={%for host in groups['master']%}"{{hostvars[host].ansible_default_ipv4.address}}:{{ port }}"{% if not loop.last %},{% endif %}{% endfor %}

- debug: msg=[{{nodelist1}}]

- name: Download the Heart Beat File
  become: true
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/heartbeat/heartbeat-{{ elastic_version }}-amd64.deb
    dest: /tmp
    mode: 0440
  when: elastic_flavor is defined and elastic_flavor == "pgdg"

- name: Installing Heart Beat 
  become: true
  apt:
    deb: /tmp/heartbeat-{{ elastic_version }}-amd64.deb

- name: Update apt-get repo and cache
  become: true
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Enabling Heart Beat Search Output
  become: true
  template:
    src: heartbeat.yml.j2
    dest: '/etc/heartbeat/heartbeat.yml'
  when: individual == "flase"

- name: Enabling heartbeat Search Output
  become: true
  template:
    src: heartbeat_individual.yml.j2
    dest: '/etc/heartbeat/heartbeat.yml'
  when: individual == "true"

- name: Enabling the Heart Beat service
  become: true
  command: "systemctl enable heartbeat"

- name: Starting the Heart Beat service
  become: true
  command: "systemctl start heartbeat"

- name: Status of the Heart Beat
  become: true
  command: "systemctl status heartbeat"

- name: Restarting the Heart Beat service
  become: true
  command: "systemctl restart heartbeat"