---
- name: Download the filebeat File
  become: true
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ elastic_version }}-amd64.deb
    dest: /tmp
    mode: 0440
  when: elastic_flavor is defined and elastic_flavor == "pgdg"

- name: Installing Filebeat 
  become: true
  apt:
    deb: /tmp/filebeat-{{ elastic_version }}-amd64.deb

- name: Changing the filebeat config file
  become: true
  template:
    src: filebeat.yml.j2
    dest: '/etc/filebeat/filebeat.yml'

- name: Update apt-get repo and cache
  become: true
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Enabling the Filebeat service
  become: true
  command: "systemctl enable filebeat"

- name: Starting the Filebeat service
  become: true
  command: "systemctl start filebeat"

- name: Status the elastic Filebeat
  become: true
  command: "systemctl status filebeat"

- name: Restarting the Filebeat service
  become: true
  command: "systemctl restart filebeat"