---

# Downloading the logstash File in deb
- name: Download the Logstash File
  become: true
  get_url:
    url: https://artifacts.elastic.co/downloads/logstash/logstash-{{ elastic_version }}-amd64.deb
    dest: /tmp
    mode: 0440
  when: elastic_flavor is defined and elastic_flavor == "pgdg"

- name: Installing the logstash File
  become: true
  apt:
    deb: /tmp/logstash-{{ elastic_version }}-amd64.deb

- name: Update apt-get repo and cache
  become: true
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Enabling the logstash service
  become: true
  command: "systemctl enable logstash"

- name: Starting the logstash service
  become: true
  command: "systemctl start logstash"

- name: Status the logstash service
  become: true
  command: "systemctl status logstash"





