---
- name: Create List of nodes to be added into Cluster
  set_fact: nodelist={%for host in groups['all']%}"{{hostvars[host].ansible_default_ipv4.address}}"{% if not loop.last %},{% endif %}{% endfor %}

- debug: msg=[{{nodelist}}]

- name: Create List of master nodes to be added into Cluster
  set_fact: nodelist1={%for host in groups['master']%}"{{hostvars[host].ansible_default_ipv4.address}}"{% if not loop.last %},{% endif %}{% endfor %}

- debug: msg=[{{nodelist1}}]

- name: Create List of master nodes to be added into Cluster
  set_fact: nodelist2={%for host in groups['master']%}"http://{{hostvars[host].ansible_default_ipv4.address}}:{{port}}"{% if not loop.last %},{% endif %}{% endfor %}

- debug: msg=[{{nodelist2}}]
# Downloading the Elastic File in deb
- name: Download the Elastic File
  become: true
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elastic_version }}-amd64.deb
    dest: /tmp
    mode: 0440
  when: elastic_flavor is defined and elastic_flavor == "pgdg"

- name: Installing the Elastic File
  become: true
  apt:
    deb: /tmp/elasticsearch-{{ elastic_version }}-amd64.deb

- name: Update apt-get repo and cache
  become: true
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Create data directory
  become: true
  file:
    path: "/{{ data_path }}/elasticsearch"
    state: directory

- name: Create log directory
  become: true
  file:
    path: "/{{ log_path }}/elasticsearch"
    state: directory

- name: Changing the elastic config file
  become: true
  template:
    src: elasticsearch.yml.j2
    dest: '/etc/elasticsearch/elasticsearch.yml'


- name: Adding parameter to config
  become: true
  lineinfile:
    path: /etc/security/limits.conf
    line: 'elasticsearch soft memlock unlimited
           elasticsearch hard memlock unlimited'

- name: Adding parameter to config
  become: true
  lineinfile:
    path: /usr/lib/systemd/system/elasticsearch.service
    line: 'LimitMEMLOCK=infinity'


- name: Enabling the elastic service
  become: true
  command: "systemctl enable elasticsearch"

- name: Starting the elastic service
  become: true
  command: "systemctl start elasticsearch"

- name: Status the elastic service
  become: true
  command: "systemctl status elasticsearch"

- include_tasks: kibana.yml
  when: node_name == "node-1"

- name: Stopping the elastic service
  become: true
  command: "systemctl stop elasticsearch"

- name: Stopping the elastic service
  become: true
  command: "systemctl stop kibana"

- include_tasks: security_cert.yml
  when: node_name=="node-1"

- include_tasks: Chaning_paswords.yml
  when: node_name=="node-1"

- include_tasks: copying_cert.yml
  when: node_name!="node-1"

- include_tasks: kibana_security.yml
  when: node_name=="node-1"

- name: restart the Kibana service
  become: true
  command: "systemctl restart kibana"

